todo_list_project/todo_list/urls.py
#urls.py
from django.contrib import admin  
from django.urls import path  
from todo_list import views  
from django.contrib.auth import views as auth_views

urlpatterns = [  
    path('admin/', admin.site.urls),  
    #path('', views.index),  
    path('addnew',views.addnew),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
    path('', views.index, name='home'),
    path('register/', views.register, name='register'),
  
    path('login/', auth_views.LoginView.as_view(template_name='todo_list/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='todo_list/logout.html'), name='logout'),
] 

todo_list_project/todo_list_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_list.urls')),
]

todo_list_project/todo_list/models.py
from django.db import models

class TodoTask(models.Model):  
    title = models.CharField(max_length=100)  
    description = models.TextField(max_length=400) 
    duedate = models.DateField()
    complete = models.BooleanField(default=False)
    createuser =  models.CharField(max_length=100) 
  
    class Meta:  
        db_table = "todotask"

todo_list_project/todo_list/forms.py
from django import forms  
from todo_list.models import TodoTask 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class TodoTaskForm(forms.ModelForm):  
    class Meta:  
        model = TodoTask  
        fields = ['title', 'description', 'duedate', 'complete','createuser'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = { 'title': forms.TextInput(attrs={ 'class': 'form-control' }), 
            'description': forms.Textarea(attrs={ 'class': 'form-control rounded-0','rows':'5' }),
            'duedate': forms.DateInput(attrs={ 'class': 'form-control','type' : 'date' }),
            'complete':forms.CheckboxInput(attrs={ 'class': 'form-check-input me-2' }),
            'createuser':forms.TextInput(attrs={ 'class': 'form-control','value':User.username })
      }

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=101)
    last_name = forms.CharField(max_length=101)
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

todo_list_project/todo_list/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import HttpResponseNotFound
from django.contrib.auth import login, authenticate
from django.contrib import messages
from .forms import UserRegistrationForm
from django.template.loader import render_to_string

#views.py
from django.shortcuts import render, redirect  
from todo_list.forms import TodoTaskForm  
from todo_list.models import TodoTask  
# Create your views here.  


def addnew(request):  
    if request.method == "POST":  
        form = TodoTaskForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/')  
            except:  
                pass 
    else:  
        form = TodoTaskForm()  
    return render(request,'todo_list/index.html',{'form':form}) 

 
def index(request):  
    todolist = TodoTask.objects.filter(createuser=request.user.username).values()
    return render(request,"todo_list/show.html",{'todolists':todolist}) 

 
def edit(request, id):  
    try:
        todolist = TodoTask.objects.get(id=id)  
        return render(request,'todo_list/edit.html', {'todolist':todolist}) 
    except:
        response_data = render_to_string("todo_list/404.html")
        return HttpResponseNotFound(response_data)


 
def update(request, id):  
    todolist = TodoTask.objects.get(id=id)  
    form = TodoTaskForm(request.POST, instance = todolist)  
    if form.is_valid():  
        form.save()  
        return redirect("/")  
    return render(request, 'todo_list/edit.html', {'todolist': todolist})  


def destroy(request, id):  
    todolist = TodoTask.objects.get(id=id)  
    todolist.delete()  
    return redirect("/") 

def home(request):
    return render(request, 'todo_list/home.html')

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()

            messages.success(request, f'Your account has been created. You can log in now!')    
            return redirect('login')
    else:
        form = UserRegistrationForm()

    context = {'form': form}
    return render(request, 'todo_list/register.html', context)

todo_list_project/todo_list/templates/todo_list/base.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
<meta charset="UTF-8">  
<title>{% block title %}{% endblock %}</title>
{% load static %}  
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
 
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
</head> 
<body>
<div class="container">
 <div class="row">
    {% block content %}{% endblock %}
 </div>
</div>
<script>
$(document).ready(function() {
    $('#bootstrapdatatable').DataTable({     
      "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
        "iDisplayLength": -1
       } 
    );
} );
</script>
</body> 
</html>

todo_list_project/todo_list/templates/todo_list/edit.html
{% extends "todo_list/base.html" %}
 
{% block title %}Add New To_do list Records{% endblock title %}
 
{% block content %}
{% include 'todo_list/navbar.html' %} 
{% if user.is_authenticated %}
<div class="col-md-12">
   
 <form method="POST" class="post-form" action="/update/{{todolist.id}}">  
   {% csrf_token %}  
  <div class="container">  
 <br>  
  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <h3>Update Details</h3>  
  </div>  
   </div>  
  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Id:</label>  
  <div class="col-sm-4">  
   <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ todolist.id }}"/>  
  </div>  
   </div>  
   <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Title:</label>  
  <div class="col-sm-4">  
   <input type="text" class="form-control" name="title" id="id_title" required maxlength="100" value="{{ todolist.title }}" />  
  </div>  
   </div>  
  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Description:</label>  
  <div class="col-sm-4"> 
    <textarea class="form-control" id="id_description" rows="5" name="description" >{{ todolist.description }}</textarea>
  </div>  
   </div>  
  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Due Date:</label>  
  <div class="col-sm-4">  
   <input type="date" class="form-control" name="duedate" id="id_contact" required maxlength="15" value="{{ todolist.duedate | date:'Y-m-d' }}" />  
  </div>  
   </div>  
   <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Complete:</label>  
    <div class="col-sm-4"> 
     <input type="checkbox" class="form-check-input me-2" name="complete" {% if todolists.complete == 1 %} checked="checked" value="1" {% endif %}/>   
    </div>  
     </div> 
  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <button type="submit" class="btn btn-success btn-lg">Update</button>  
  <input type="hidden" class="form-control" name="createuser" id="id_title" required maxlength="100" value="{{ todolist.createuser }}" />  
  </div>  
   </div>  
  </div>  
 </form>
 {% else %}
    <div class="alert alert-success" role="alert">
        <h3>Welcome!</h3>
        <a href="{% url 'register' %}">Signup</a>
        <a href="{% url 'login' %}">Login</a>
    </div>
{% endif %}  
{% endblock content %}  

todo_list_project/todo_list/templates/todo_list/home.html
{% extends 'todo_list/base.html' %}


{% block content %}
{% if user.is_authenticated %}
    <div class="alert alert-success" role="alert">
        <h3>Welcome {{ user.username }}!</h3>
        <a href="{% url 'logout' %}">Logout?</a>
    </div>
{% else %}
    <div class="alert alert-success" role="alert">
        <h3>Welcome!</h3>
        <a href="{% url 'register' %}">Signup</a>
        <a href="{% url 'login' %}">Login</a>
    </div>
{% endif %}
{% endblock content %}

todo_list_project/todo_list/templates/todo_list/index.html

{% extends "todo_list/base.html" %}
 
{% block title %}Add New To_do List Records{% endblock title %}
 
{% block content %}
{% include 'todo_list/navbar.html' %} 
{% if user.is_authenticated %}
<div class="col-md-12">
   
 <form method="POST" class="post-form" action="/addnew">  
   {% csrf_token %}  
  <div class="container">  
 <br>  
  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <h3>Enter To_do Task Details</h3>  
  </div>  
   </div>  
   
   <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Title:</label>  
  <div class="col-sm-4">  
    {{ form.title }}  
  </div>  
   </div>  
  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Description:</label>  
  <div class="col-sm-4">  
    {{ form.description }}  
  </div>  
   </div>  
  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Due Date:</label>  
  <div class="col-sm-4">  
    {{ form.duedate }}  
  </div>  
   </div>  
   <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Complete:</label>  
    <div class="col-sm-4">  
      {{ form.complete}}  
    </div>  
     </div>
  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <button type="submit" class="btn btn-primary">Submit</button> 
  <input type="hidden" class="form-control" name="createuser"  value=" {{ user.username }}" /> 
  </div>  
   </div>  
  </div>  
 </form>  
</div> 
{% else %}
    <div class="alert alert-success" role="alert">
        <h3>Welcome!</h3>
        <a href="{% url 'register' %}">Signup</a>
        <a href="{% url 'login' %}">Login</a>
    </div>
{% endif %}
{% endblock content %} 

todo_list_project/todo_list/templates/todo_list/login.html
{% extends 'todo_list/base.html' %}


{% block content %}
{% include 'todo_list/navbar_logout.html' %} 
<h3>login</h3>
<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
        <p>{{ field.label }}: <br> {{ field }}</p>
    {% endfor %}
    <button type="submit">Login</button>
</form>
{% if form.errors %}
<div class="alert alert-danger">
   username or password not correct..
  </div>
{% endif %}
<p>Don't have an account? <a href="{% url 'register' %}">Signup here</a></p>

{% endblock content %}

todo_list_project/todo_list/templates/todo_list/logout.html
{% extends 'todo_list/base.html' %}

{% block content %}
{% include 'todo_list/navbar_logout.html' %} 
    <br>
    <div class="alert alert-success" role="alert">
        <h2 style="text-align: center;">Logged out! <a href="{% url 'login' %}">ClickLogin</a> <br></h2>
    </div>

{% endblock content %}

todo_list_project/todo_list/templates/todo_list/navbar.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Todo_Task</a>
      </div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'home' %}">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
      </ul>
    </div>
  </nav>

todo_list_project/todo_list/templates/todo_list/navbar_logout.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header navbar-center">
        <a class="navbar-brand" href="#">Welcome Todo_List </a>
      </div>
     
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'register' %}"><span class="glyphicon glyphicon-user"></span> Register</a></li>
        <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </nav>

todo_list_project/todo_list/templates/todo_list/register.html
{% extends 'todo_list/base.html' %}


{% block content %}
{% include 'todo_list/navbar_logout.html' %} 
<h3>Register here</h3>
<hr>

<form action="" method="POST">
    {% csrf_token %}

    {% for field in form %}
        <div>
            <p>{{ field.label }}: <br> {{ field }}</p> 

            {% for error in field.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
        </div>
    {% endfor %}
    <button type="submit">Register</button>
</form>
{% endblock content %}

todo_list_project/todo_list/templates/todo_list/show.html

{% extends "todo_list/base.html" %}
 
{% block title %}To_do Task{% endblock title %}
 
{% block content %}
{% include 'todo_list/navbar.html' %} 
{% if user.is_authenticated %}
 <div class="col-md-12">
        <span><a href="/addnew" class="btn btn-primary">Add New To_do Task</a></span>  
        <div class="table-responsive">
  <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
               
                <th style="display:none;">ID</th>
                <th>Title</th>
                <th>Description</th>
                <th>Due Date</th>
                <th>Complete</th>
                <th>Edit</th>
                <th>Delete</th>
             </thead>
   <tbody>
   {% for todolist in todolists %}  
    <tr>  
     <td style="display:none;">{{ todolist.id }}</td>  
     <td>{{ todolist.title }}</td>  
     <td>{{ todolist.description }}</td>  
     <td>{{ todolist.duedate }}</td>  
     <td><input type="checkbox" disabled="disabled" {% if todolist.complete == 1 %} checked="checked" {% endif %} /></td>  
     <td><p data-placement="top" data-toggle="tooltip" title="Edit"><a href="/edit/{{ todolist.id }}" class="btn btn-primary btn-xs" {% if todolist.complete == 1 %} disabled="disabled" {% endif %} data-title="Edit" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil"></span></a></p></td>
     <td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="/delete/{{ todolist.id }}" class="btn btn-danger btn-xs" {% if todolist.complete == 1 %} disabled="disabled" {% endif %} data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash"></span></a></p></td>  
    </tr>  
   {% endfor %} 
   </tbody>
         
  </table>
        </div>
    </div>
{% else %}
    <div class="alert alert-success" role="alert">
        <h3>Welcome!</h3>
        <a href="{% url 'register' %}">Signup</a>
        <a href="{% url 'login' %}">Login</a>
    </div>
{% endif %}
{% endblock content %}